repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length=125]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: utility-repo-scripts/ensure_venv.sh
        language: script
        types: [python]
        exclude: ^alembic/
        args: [pylint, -v, --rcfile=.pylintrc]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check # Configure in .gitattributes
      - id: git-dirty # Configure in .gitignore
      - id: markdownlint # Configure in .mdlrc
      - id: shellcheck
      - id: shfmt
