#!/bin/bash
git submodule update --init --remote
rebuild_venv=$1
rebuild_venv="${rebuild_venv:-0}"
# source utility-repo-scripts/setup_python_app.sh -d 1 -s 1 -l 1 -v 3 -r "$rebuild_venv"
source utility-repo-scripts/setup_python_app.sh --debug=1 --overwrite_vscode_settings=1 --overwrite_vscode_launch=1 --setup_version=3 --rebuild_venv="$rebuild_venv" --python_formatter=black --python_linter=pylint --python_testing_framework=pytest
